#!/usr/bin/env python
import rate_conversions as rc
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("mass", type=float)
parser.add_argument("phase_space", type=float)
parser.add_argument("nuc_mat_el", type=float)
args = parser.parse_args()

m = rc.expected_bb_events(args.mass, args.phase_space, args.nuc_mat_el,
                           rc.SNOT_MASS, rc.SNOT_LOADING, rc.TE_130_ABUNDANCE,
                           rc.TE_130_MASS)

hl = rc.mass_to_hl(args.mass, args.phase_space, args.nuc_mat_el)

print "For a mbb of {0} \n\t\t--> G =  {1} \n\t\t--> |M| = {2} \n We would expect {3} events \n\t Equivalent to a half-life of {4}".format(args.mass, args.phase_space, args.nuc_mat_el, m, hl)
